version: 2.1

orbs:
  node: circleci/node@4.0.1

parameters:
  version:
    type: string
    default: 1.2.1

general:
  branches:
    - master

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/Carbon-Client-<< pipeline.parameters.version >>

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Decompiling workspace
          command: |
            ./gradlew setupDecompWorkspace
      - run:
          name: Build.
          command: |
            ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/libs/

      - node/install:
          install-yarn: true
